import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".next-export/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Capacitor native shell (generated by `npx cap add android`, gitignored)
    "android/**",
  ]),
]);

export default eslintConfig;
